language: node_js
node_js:
- '4.0'
- '4'
- '5'
- '6.0'
- '6'
- '7'
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: '9.5'
sudo: false
script: npm run lint && npm test
after_success:
- cat coverage/lcov.info | node_modules/.bin/coveralls
notifications:
  email: false
  slack:
    secure: exqsUXkeb46CQi9bcMXD7AgIagaEi3kTnOddgz3DWotXpZMRgn3uYpEZPjHUvBM43nw9eVn5SCTlem/YXVsOynXExn+eV/ouX3mf62ASItyilBtYGzGBZGDCiQh0z7xyPwZtFm64ijEJVY89wvE2PDJ5hXQVV16nafkG9EgeGFCaN3iYlxg35hDptmYA3UZ2aLbFwUYDDi4l5PaUDtOfqdxXfAngBP7xxYe+0DFZ5ekhGnfIsKw20VFKAfc7oC/nZ7VCujcMVIgGHQEokAfIxvTTHmdYiaPvaoPLSGah2ehKFskaQo0MBXZHumkTHcSZoKeTKoXKF41WiXknn4npsxF6qwF/DDJv5DJXbcR2EeShnJa24MwfeuzZHoIbvEJthSShXmBtT4m2iEG55HisuhUHWBSyYlTFDXJT4zZxSa7S6pR9Ge24X/g/tC4h7mlu3k+3JxhWQ02pcPtSGSZvqrW8n4PyuB9rU5hoj2kJDuYbIg/Xas7a9Ipl9ySqD3RU9iTgk2KqG0AVexw99juH+1tXCUrUtdSedkLMKaASu4qy9ZkP6GXUFAofWP5zlyEjLCvDXNfrq4oVFUfMD2jlqvlx5uWBBejclRWOCwb5Kp2ZwSsDX6WFFgFoyGPFeDiEpD5peW4p3yhDG39ZtIsm1Qbih5CFD8JXkT+DyCS0/Gk=
branches:
  only:
  - master
  - develop
